name: Deploy staging env
on:
  push:
    branches: [ staging ]
env:
  DEPLOY_ENV: test
  DNAME: test
  CI: ${{ secrets.CI }}
  API_KEY: ${{ secrets.API_KEY }}
  APP_ID: ${{ secrets.APP_ID }}
  AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
  IS_DEPLOY: ${{ secrets.IS_DEPLOY }}
  MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }}
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
  DATABASE: ${{ secrets.DATABASE }}
  DATABASE_USER: ${{ secrets.DATABASE_USER }}
  DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}
  JWT_COOKIE_EXPIRES_IN: ${{ secrets.JWT_COOKIE_EXPIRES_IN }}
  MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
  MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
  OAUTH_CLIENTID: ${{ secrets.OAUTH_CLIENTID }}
  OAUTH_CLIENT_SECRET: ${{ secrets.OAUTH_CLIENT_SECRET }}
  OAUTH_ACCESS_TOKEN: ${{ secrets.OAUTH_ACCESS_TOKEN }}
  OAUTH_REFRESH_TOKEN: ${{ secrets.OAUTH_REFRESH_TOKEN }}
  EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
  LANDING_URL: ${{ secrets.LANDING_URL }}
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Disable update
        run: npm config set update-notifier false
      - name: Print envs
        run: |
          echo "DEPLOY_ENV: $DEPLOY_ENV"
          echo "DNAME: $DNAME"
          echo "CI: $CI"
          echo "API_KEY: $API_KEY"
          echo "APP_ID: $APP_ID"
          echo "AUTH_DOMAIN: $AUTH_DOMAIN"
          echo "IS_DEPLOY: $IS_DEPLOY"
          echo "MESSAGING_SENDER_ID: $MESSAGING_SENDER_ID"
          echo "PROJECT_ID: $PROJECT_ID"
          echo "STORAGE_BUCKET: $STORAGE_BUCKET"
          echo "DATABASE: $DATABASE"
          echo "DATABASE_USER: $DATABASE_USER"
          echo "DATABASE_PASSWORD: $DATABASE_PASSWORD"
          echo "JWT_SECRET: $JWT_SECRET"
          echo "JWT_EXPIRES_IN: $JWT_EXPIRES_IN"
          echo "JWT_COOKIE_EXPIRES_IN: $JWT_COOKIE_EXPIRES_IN"
          echo "MAIL_USERNAME: $MAIL_USERNAME"
          echo "MAIL_PASSWORD: $MAIL_PASSWORD"
          echo "OAUTH_CLIENTID: $OAUTH_CLIENTID"
          echo "OAUTH_CLIENT_SECRET: $OAUTH_CLIENT_SECRET"
          echo "OAUTH_ACCESS_TOKEN: $OAUTH_ACCESS_TOKEN"
          echo "OAUTH_REFRESH_TOKEN: $OAUTH_REFRESH_TOKEN"
          echo "EMAIL_FROM: $EMAIL_FROM"
          echo "LANDING_URL: $LANDING_URL"
      - name: Download deps
        run: npm install
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}