name: Deploy main env
on:
  push:
    branches: [ main ]
env:
  CI: ${{ secrets.CI }}
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Disable update
        run: npm config set update-notifier false
      - name: Create env file
        run: |
          touch .env
          echo "${{ secrets.PRODUCTION_ENV_VARS }}" >> .env
      - name: Download deps
        run: npm ci && npm install -g firebase-tools
      - name: Deploy to Firebase
        run: firebase deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}